
%结构体参数
%定义结构体
% caCfarPara.gap 		= CfarN;        %保护单元个数
% caCfarPara.width 		= CfarM;        %输入滑动窗长度
% caCfarPara.factor 	= CfarFactor;	%门限因子
% caCfarPara.offset		= CfarOffset;	%门限直流偏置量
% caCfarPara.cfarType	= 0;            %输入滑动平均处理方式0:滑动平均;1:滑动平均选大; 2:滑动平均选小
% caCfarPara.boundary	= 0;            %边界处理方式0:固定值;1:单边门限值
CACFARPARA = struct('gap', 0.0, 'width', 0.0, 'cfarType', 0.0, 'factor', 0.0, 'offset', 0.0, 'boundary', 0.0);		

%目标信息
TARGETPARA = struct(...
                    'Rrange',           0.0, ...        % 目标距离，米
                    'Vr',               0.0, ...        % 目标速度，m/s
                    'Angle',            0.0, ...        % 方位角度,度
                    'Raz',              0.0, ...        % 目标方位向距离（角度转距离），米
                    'Amp',              0.0  ...        % 信号幅度
                    );
                
%记录所有帧所有点迹
TARGOUT = struct(... 
                'ValidFlag',        0.0, ...            %检测是否有效，0：没捡到目标，1：检到目标
                'TargetNum',        0.0, ...            %检测到的目标个数
                'TargetPara',       repmat(TARGETPARA, 1, TargNumMax) ...
                );

 %定义航迹相关参数
 TRACKTHRESH = struct(... 
                        'deltaX',           0.0, ...        %窗口大小，用于矩形波门判断
                        'deltaY',           0.0, ...
                        'deltaR',           0.0 ...         %窗口大小，用于圆形波门判断
                        );
            
%记录点迹信息，用于预测滤波
DOTPARA = struct(...
                'ID',               0.0, ...                %序号
                'FrameTime',    0.0, ...            %驻留周期
                'Rlast',            0.0, ...                %上一拍距离
                'Vlast',            0.0, ...
                'Zlast',            0.0, ...
                'Rnow',             0.0, ...                %当前拍距离
                'Vnow',             0.0, ...
                'ZNow',             0.0, ...            
                'Rpredict',         0.0, ...                %预测值
                'Vpredict',         0.0, ...
                'Zpredict',         0.0, ...
                'Rafter',           0.0, ...                %滤波后的值
                'Vafter',           0.0, ...
                'Zafter',           0.0 ...
                );
    DOTOUT = struct(... 
                'ValidFlag',        0.0, ...            %检测是否有效，0：没捡到目标，1：检到目标
                'DotNum',        0.0, ...            %检测到的目标个数
                'DotPara',       repmat(DOTPARA, 1, TargNumMax) ...
                );        
   %航迹信息
   TRACKS = struct(...
                'ID',               0.0, ...
                'box',              0.0, ...
                'Range',          0.0, ...
                'Zmeter',         0.0, ...
                'age',              0.0, ...
                'totalVisibleCount',            0.0, ...        %轨迹可见帧数
                'invisibleCount',              0.0 ...          %不可见计数
                );
            
            
            
